---
all:
  hosts:
    chefserver:
  children:
    prod:
     hosts:
        chefclient01:
          ansible_port: 2222
        chefclient02:
        chefclient03:
        chefclient04:
        chefclient05:
        chefclient06:
        chefclient07:
        chefclient08:
        chefclient09:
    dev:
      hosts:
        chefclient06:
        chefclient07:
        chefclient08:
        chefclient09:
        chefclient10:
        chefclient11:
...
