---
- name : Remove MOTD 
  hosts : all 
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: false

  vars:
     motd: "Welcome to CentOS Linux - Updated by Ansbile \n"


  tasks: 
    - name: Remove Motd file in Linux Client 
      file: 
        path: /etc/motd
        state : absent

  handlers:
    - name: MOTD Remove 
      debug:
       msg: The MOTD file was removed


...
