---
- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: false

  vars_files:
      - /home/ansible/users.yml
  tasks:
   - name: adding multi_users
     user:
      name: "{{ item.name }}"
      state: present
      comment: "{{ item.comment }}"
      groups: "{{item.groups }}"
     with_items: "{{ users }}"
...
